### PR TITLE
Support announcement threads, private threads, voice text channels and stage text channels

### PR DESCRIPTION
**Pull request by Happypig375**

### CODE REVIEW

**Comment by Happypig375** [comment]
Should voice channels be supported too to send text inside? They do support text messages but no one I know really uses it because too inconvenient

**Comment by laralove143** [comment]
thanks for the pr!

voice text channels (lovely phrase) should be supported but there isnt a separate channel type for them maybe putting `ChannelType.GUILD_VOICE` in `Component.ChannelTypes` is the way to do it

could you test this pr maybe taking the voice channel support into its scope and lmk if it works

**Comment by Happypig375** [comment]
I don't have Rust installed but at least Stackoverflow tells me it works https://stackoverflow.com/questions/72928111/how-to-send-a-message-to-the-chat-in-a-voicechannel-using-discord-py

**Comment by laralove143** [comment]
did some testing

- private threads work BUT the bot has to be mentioned in them first, this is expected but the problem is the bot doesnt tell this properly and it just says the permissions its missing, this is a niche case so ill merge it and create an issue for addressing this
- announcement threads work
- stage channels say that the bot doesnt have the permissions it needs when it does and voice channels say that the user (not the bot) doesnt have send messages permission both of these require additional handling which i dont have the bandwidth to do

please remove stage and voice channels from this pr and ill merge it

**Comment by laralove143** [comment]
this is now deployed, feel free to reopen if theres any issues

**Pull request merged**
