### PR TITLE
Implemented support for attachments

### PR DESCRIPTION
**Pull request by Rayrsn**
The attachment implementation also includes support for spoilers and alt tags
This pull request possibly closes (`move old messages and messages with attachments` #11)

### CODE REVIEW

**Comment by laralove143** [comment]
thank you for the work but i wish you'd asked before implementing this, as ive said in the server before, reuploading images isnt a viable option at scale

considering that attachments by non-nitro members can be up to 25mb and the number of attachments people are trying to move, uploading that much data would be costly both in terms of bandwidth and hardware resources, server providers charge per amount of egress data, which i personally cant afford to pay for and since this bot is free i would have to pay for it

you're free to self-host your fork though

**Comment by Rayrsn** [comment]
That's completely fine! I also didn't check out your server before making the changes.
We can leave this here just in case someone wants this feature on their own self-hosted version

**Comment by laralove143** [comment]
having options is always great, thanks for the pr again, im closing this now

**Comment by aegis72** [comment]
Noted; probably want to modify the error message then, as it implies this is something in development.

**Comment by laralove143** [comment]
the bot is admittedly dead in many ways, i just dont have the bandwidth to maintain it sadly and i dont really know when i will get that time but it is in my backlog that im struggling to move through

**Pull request closed without merging**
